#!/usr/bin/env bash
#MISE description="Show backend database"

set -e

echo "🔍 Display data in the users and files tables"


cd "${MISE_CONFIG_ROOT}/backend"

echo ""
echo "📝 Users table:"
docker compose exec postgresql psql -U db_user -d datashare -c "SELECT * FROM users;"
echo ""
echo ""
echo "📝 Files table:"
docker compose exec postgresql psql -U db_user -d datashare -c "SELECT * FROM files;"