#!/usr/bin/env bash
#MISE description="Install Python dependencies in venv"
#MISE arg "--no-pip-upgrade" help="do not upgrade pip" default="true"

set -e

prerequisites=(
    "python3" 
    "pip" 
    "docker"
    # frontend 
    "npm" 
    "node"
    # backend
    "mvn" 
    "java"
)

for cmd in "${prerequisites[@]}"; do
    if ! command -v $cmd &> /dev/null; then
        echo "❌ $cmd could not be found. Please install $cmd."
        exit 1
    fi
done

mkdir -p ${MISE_CONFIG_ROOT}/logs

if [ ! -f ${MISE_CONFIG_ROOT}/backend/.env ]; then
    echo "Creating default .env file for backend..."
    cat << EOF > ${MISE_CONFIG_ROOT}/backend/.env
PG_VERSION=16.1-alpine
DB_USER=db_user
DB_PASSWORD=oc2025-db_user!
DB_HOST=postgresql
DB_PORT=5432
DB_NAME=datashare

# CORS - Allow frontend access from any local network IP
CORS_ALLOWED_ORIGINS=http://localhost:4200,http://127.0.0.1:4200,http://192.168.10.163:4200,http://frontend:4200

# Download URL - Public URL pointing to frontend download page (US01)
# This URL is shared with users to access the download page
DOWNLOAD_BASE_URL=https://www.datashare.projet3.oc/download
EOF
    echo "✅ .env file for backend created!"
else
    echo ".env file for backend already exists. Skipping creation."
fi


echo "Installing dependencies..."
if [ "${MISE_ARG_NO_PIP_UPGRADE}" == "true" ]; then
    pip install --upgrade pip
    echo "✓ pip upgraded!"
fi

pip install -r requirements.txt
echo "✓ Dependencies installed!"
