#!/usr/bin/env bash
#MISE description="Show app data"

set -e

echo "🔍 Display data in the users and files tables"


cd "${MISE_CONFIG_ROOT}"

echo ""
echo "📝 Users table:"
docker compose exec postgres psql -U db_user -d datashare -c "SELECT * FROM users;"
echo ""
echo ""
echo "📝 Files table:"
docker compose exec postgres psql -U db_user -d datashare -c "SELECT * FROM files;"
echo ""
echo ""
echo " Files stored on the server:"
docker compose exec backend ls -laR /var/datashare/storage
echo ""
echo "✅ Data display complete."